% This script makes the default structures required for the slipBERI code

clear all

fault = struct('fault_descriptor_file', 'napa_geom_ruth2f.txt',...
                'fault_coordinate_unit', 'utm');

data = struct('InSAR_datafile', {{'140807-140831_corrected.6cols'}}, ...
              'InSAR_coordinate_unit', 'utm',...
              'varcovar_details', {{'napa_covar.txt'}},...
              'quadtree_n_points', {{'nesteddownsample_npoints.txt'}},...
              'GPS_datafile_2d', '20140831-20140823_2d_gps.7cols',...
              'GPS_datafile_3d', '20140831-20140823_3d_gps.7cols',...
              'GPS_coordinate_unit', 'long/lat',...              
              'atolls_datafile', 'none',...
              'weight_InSAR', 1,...
              'weight_GPS', 1,...
              'weight_atolls', 1,...
              'UTMzone', 10,...
              'origin', [133.815 35.368],...
              'EQ_epicenter', [38.215, -122.312, 11.1], ...     % http://earthquake.usgs.gov/earthquakes/eventpage/nc72282711#origin
              'seismic_moment', 2.818e+18, ... 
              'moment_std', 2.1310e+17,...
              'mindist', 0);


invert = struct('quickcheck', 'yes',...
                'inversion_type', 'bayesian', ...      
                'iterations', 200000, ...            
                'smoothing', 'VK',...                
                'smooth_across_fault_strands', 'yes',... 
                'slip_initial', 0.7, ...                 
                'step_size', 0.005, ...                  
                'variable_rake', 'yes',...            
                'solve_for_InSAR_offset', 'no',...
                'solve_for_InSAR_ramp', 'no',...
                'regularise_moment', 'no', ...         % or 'no'
                'alpha2_initial', 0.5,...
                'alpha2_step_size', 0.01,...  
                'probability_target_initial', 0.001, ...
                'solve_for_beta', 'no',...
                'beta_initial', 1,...
                'beta_step_size', 0.01,...
                'simulated_annealing_start', 'no',...
                'solve_for_fault_size', 'no',...
                'add_correlation_matrix_stabiliser', 'no',...
                'load_old_MCMC_chain', 'no');
      
            
priors = struct('slip_prior', 'boxcar', ...            
                'min_slip', 0, ...                  
                'max_slip', 50, ... 
                'predominant_faulting_style', {{'ss'}},...
                'min_rake', 150,...                
                'max_rake', 210,...                   
                'alpha2_prior', 'logarithmic',...
                'min_alpha2', 0.001,...
                'max_alpha2', 2,...
                'alpha2flag', [],...
                'min_offset', -1,...
                'max_offset', 1,...
                'min_beta', 1,...
                'max_beta', 1,...
                'min_circharm_coeffs', [],...
                'max_circharm_coeffs', [],...
                'min_circharm_phi', [],...
                'max_circharm_phi', [],...
                'min_circharm_center', [],...
                'max_circharm_center', []);


elastic_params = struct('lambda', 3.23e10,...
                        'mu_okada', 3.23e10);

display = struct('plot_resolution_matrix', 'no',...     
                 'plotmean', 'no',...                        % other option: 'yes'
                 'plotmode', 'no',...                        % other option: 'yes'
                 'plotmedian', 'no',...                      % other option: 'no'              
                 'plotmaxlikely', 'yes',...                  % other option: 'yes'  % IN FUTURE VERSIONS THIS WILL BE DELETED, coz I've replaced it with MAP
                 'plotallslips', 'yes',...                   % other option: 'no'
                 'plotprob', 'yes',...                       % other option: 'no'
                 'plothists', 'plothistsall',...              % other option: 'plothistsample' (i.e. choose some at random to plot)
                 'plotsurfacedisp', 'yes',...                % other option: 'no'
                 'plotmarginalPDFs', 'yes',...
                 'plotMAP', 'yes',...
                 'plot3d', 'yes') ;                % other option: 'no'
             
                              
housekeeping = struct('save_name', 'napaslip');

% display all the structures so people actually look and check
disp('elastic_params'), disp(elastic_params)
disp('housekeeping ='); disp(housekeeping)
disp('display ='), disp(display)
disp('fault ='); disp(fault)
disp('data ='); disp(data)
disp('invert ='); disp(invert)


